### ISSUE TITLE
MotionLayout problems with children intercepting touch events

### ISSUE THREAD

**Issue by fefwfwefwefwefefef** [android/views-widgets-samples#101]
fff

**Comment by proxyjan** [comment]
I guess I found the problem, it's the mRegionView in the onInterceptTouchEvent of motionLayout. Somwhere in the method, it checks the bounds of event x and y with the left and right, top and bottom of the mRegoinView. I looked at the values and I saw in those problematic situations the values are a little odd, and thus the function returns false and never calls the onTouch event of the motionLayout. Values are:

good situation x 354 y 450 top 0 left 16 bottom 1280 rigt 752

bad situation (As described in the question, when 1 transition already successfully changed state to a new one and we start dragging on a touch absorbing element)

x 300 y 450 top 0 left 750 bottom 1280 right 768

As you can see, the left has 750 which is a little werid to me and I don't know the reason. I'll probably check why it has that value and update this answer, but for now I simply removed the boundCheck in the onInterceptTouchEvent in the motionLayout, since I'm not really using spicific regions for now at least.

**Comment by proxyjan** [comment]
It was the touchRegion and regionId. For a same scene and element (let's say button), for the first time when you click on it, [in the touchProcess] it works fine, but if you do a transition, then it returns a wrong view in touchProcess, regionId returns another view, which was the parent of the previous transition's scene. I don't know why this happens or is it some kind of error (considering this library is still beta, understandable). So I just overrieded the touchProcess of the MotionLayout and ignored the part which checks the bounds of the TouchRegion.

**Comment by sgueniot** [comment]
same issue, with map on background and recyclerview on top of it. map intercept all drag

**Comment by wss991** [comment]
me to
